spring.application.name=kinecore-server

# H2 Console for debugging
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:kinecore;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
